### ISSUE TITLE
1.21.1中报错问题

### ISSUE THREAD

**Issue by xiaoliunone** [Coloryr/AllMusic_Client#6]
我在给1.21.1forge中添加了allmusic模组，但是却出现了报错，换了几个版本也没啥用。以为是1.21.1不行，换了1.21，也不行
![Screenshot_20241012_222335_com_tungsten_fcl_JVMActivity](https://github.com/user-attachments/assets/7ceb11a3-e95d-4904-b9a2-79c50f3b96c0)

**Comment by Coloryr** [comment]
neoforge还是forge

**Comment by xiaoliunone** [comment]
forge

**Comment by Coloryr** [comment]
forge不支持1.20.1以上版本

**Comment by Coloryr** [comment]
好吧，还是弄好了
